[package]
name = "tapssp-project"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
csv = "1"
anyhow = "1"
thiserror = "1"
rusqlite = { version = "0.31", features = ["bundled"] }
